"""Stable seams that keep protocol, memory, verification, and runners swappable."""

from __future__ import annotations

from typing import Any, Iterable, Protocol


class MemoryStore(Protocol):
    def save(self, experience: dict[str, Any], *, event_type: str, detail: str) -> dict[str, Any]: ...
    def recall(self, *, query: str, consumer: str, limit: int, record_usage: bool) -> list[dict[str, Any]]: ...
    def reverify_due(self) -> list[dict[str, Any]]: ...


class ToolConnector(Protocol):
    def observe(self) -> Iterable[dict[str, Any]]: ...
    def inject(self, context: list[dict[str, Any]]) -> None: ...


class SimulationRunner(Protocol):
    def environment_fingerprint(self) -> dict[str, str]: ...
    def launch_and_await(self, payload: dict[str, Any]) -> Any: ...


class Verifier(Protocol):
    def verify(self, experience: dict[str, Any], request: dict[str, Any]) -> dict[str, Any]: ...
